---
- name: checkout pod definitions for daemonset & deviceplugin
  git:
    repo: 'https://github.com/zvonkok/origin-ci-gpu.git'
    dest: "{{ origin_ci_gpu_root }}"

- name: oc check project nvidia
  oc_project:
    name: "{{ openshift_project }}"
    state: present

- name: oc create deviceplugin
  shell:  oc create -f {{ origin_ci_gpu_root }}/nvidia/nvidia-device-plugin.yml

- name: verify deviceplugin is running
  shell: |
    until oc get pods -n kube-system | grep nvidia-device-plugin | grep Running; do sleep 1; done

- name: start gputest pod
  shell: oc create -f {{ origin_ci_gpu_root }}/nvidia/cuda-vector-add.yaml

- name: wait until gputest is completed
  shell: |
    until oc get pods -n {{ openshift_project }} | grep cuda-vector-add | grep Completed; do sleep 1; done


- name: verify that gputest passed
  shell: oc logs cuda-vector-add -n {{ openshift_project }} | grep PASSED
  register: cuda
  failed_when: "cuda.rc != 0"
