---
- name: checkout pod definitions for daemonset & deviceplugin
  git:
    repo: 'https://github.com/zvonkok/origin-ci-gpu.git'
    dest: /root/origin-ci-gpu

- name: load selinux policy
  shell: semodule -i /root/origin-ci-gpu/selinux/nvidia-container.pp

- name: oc new project NVIDIA
  shell: oc new-project nvidia

- name: oc create deviceplugin
  shell:  oc create -f /root/origin-ci-gpu/nvidia/nvidia-device-plugin.yml

- name: verify deviceplugin is running
  shell: |
    until oc get pods | grep nvidia-device-plugin | grep Running; do sleep 1; done


- name: start gputest pod
  shell: oc create -f /root/git/openshift-psap/blog/gpu/device-plugin/cuda-vector-add.yaml

- name: wait until gputest is completed
  shell: |
    until oc get pods | grep cuda-vector-add | grep Completed; do sleep 1; done

- name: verify that gputest passed
  shell: oc logs cuda-vector-add | grep PASSED
  register: cuda
  failed_when: "cuda.rc != 0"
