---
- name: set fact nvgpuname for future use
  set_fact: NV_GPU_NAME={{ "0xDEADBEEF" }}

- name: Do we have a CUDA enabled instance?
  shell: lspci | grep NVIDIA
  register: lsnv
  ignore_errors: yes

- set_fact: valid={{ lsnv.rc }}
- group_by: key=gpunodes-{{ valid }}
