---
- block:
    - name: Do we have a CUDA enabled instance?
      shell: lspci | grep NVIDIA
      register: lsnv
      ignore_errors: yes

    - set_fact: valid={{ lsnv.rc }}
    - group_by: key=gpunodes-{{ valid }}

  when: fixture_get_gpu_nodes
