---
- block:
    - name: upload find_nvidia_display_adapter.sh
      copy: src=find_nvidia_display_adapter.sh dest=/tmp/find_nvidia_display_adapter.sh mode=0755

    - name: do we have a CUDA enabled instance?
      shell: /tmp/find_nvidia_display_adapter.sh 0x10de
      register: lsnv
      ignore_errors: yes

    - set_fact: valid={{ lsnv.stdout }}
    - group_by: key=gpunodes-{{ valid }}

  when: fixture_get_gpu_nodes



# DEPLOY NODE feature discovery6
#oc adm policy add-scc-to-user hostnetwork -n default -z node-feature-discovery
#oc adm policy add-scc-to-user anyuid -n default -z node-feature-discovery
